import {
    pdf,
    avi,
    dll,
    eps,
    zip,
    png,
    psd,
    txt,
  } from "../../../../assets/index.js";
import FilesCard from "./FilesCard";

const allFiles = [
    <FilesCard
                src={pdf}
                fileName={"my-file.pdf"}
                name={"Citi"}
                date={"20/06/2023"}
                size={"5.5MB"}
              />,
              <FilesCard
                src={avi}
                fileName={"job-file.avi"}
                name={"Admin"}
                date={"16/5/2022"}
                size={"12.5MB"}
              />,
              <FilesCard
                src={eps}
                fileName={"my-file.eps"}
                name={"Uploader"}
                date={"16/1/2024"}
                size={"12.5MB"}
              />,
              <FilesCard
                src={psd}
                fileName={"my-file.psd"}
                name={"Abdullah"}
                date={"16/5/2021"}
                size={"15.1MB"}
              />,
              <FilesCard
                src={png}
                fileName={"my-file.png"}
                name={"Designer"}
                date={"16/5/2021"}
                size={"15.1MB"}
              />,
              <FilesCard
                src={zip}
                fileName={"my-file.zip"}
                name={"Coder"}
                date={"16/5/2021"}
                size={"15.1MB"}
              />,
              <FilesCard
                src={txt}
                fileName={"my-file.txt"}
                name={"Coder"}
                date={"16/5/2021"}
                size={"15.1MB"}
              />,
              <FilesCard
                src={psd}
                fileName={"my-file.psd"}
                name={"Abdullah"}
                date={"16/5/2021"}
                size={"15.1MB"}
              />,
              <FilesCard
                src={png}
                fileName={"my-file.png"}
                name={"Coder"}
                date={"16/5/2021"}
                size={"1.1MB"}
              />,
              <FilesCard
                src={dll}
                fileName={"my-file.dll"}
                name={"Coder"}
                date={"16/5/2021"}
                size={"10.1MB"}
              />,
              <FilesCard
                src={avi}
                fileName={"my-file.avi"}
                name={"Coder"}
                date={"16/5/2021"}
                size={"13.1MB"}
              />,
              <FilesCard
                src={eps}
                fileName={"my-file.eps"}
                name={"Coder"}
                date={"16/5/2021"}
                size={"24.1MB"}
              />,
              <FilesCard
                src={pdf}
                fileName={"my-file.pdf"}
                name={"Coder"}
                date={"16/5/2021"}
                size={"15.1MB"}
              />,
              <FilesCard
                src={dll}
                fileName={"my-file.dll"}
                name={"Coder"}
                date={"16/5/2021"}
                size={"13MB"}
              />,
              <FilesCard
                src={psd}
                fileName={"my-file.psd"}
                name={"Coder"}
                date={"16/5/2021"}
                size={"16MB"}
              />,
              <FilesCard
                src={txt}
                fileName={"my-file.txt"}
                name={"Coder"}
                date={"16/5/2021"}
                size={"15.1MB"}
              />,
              <FilesCard
                src={zip}
                fileName={"my-file.zip"}
                name={"Coder"}
                date={"16/5/2021"}
                size={"21MB"}
              />,
              <FilesCard
                src={dll}
                fileName={"my-file.dll"}
                name={"Coder"}
                date={"16/5/2021"}
                size={"11MB"}
              />,
              <FilesCard
                src={eps}
                fileName={"my-file.eps"}
                name={"Uploader"}
                date={"16/5/2021"}
                size={"19.1MB"}
              />,
              <FilesCard
                src={png}
                fileName={"my-file.png"}
                name={"Coder"}
                date={"16/5/2021"}
                size={"15.1MB"}
              />,
              <FilesCard
                src={pdf}
                fileName={"my-file.pdf"}
                name={"Coder"}
                date={"16/5/2021"}
                size={"7.1MB"}
              />,
              <FilesCard
                src={psd}
                fileName={"my-file.psd"}
                name={"Abdullah"}
                date={"16/5/2021"}
                size={"9.2MB"}
              />,
              <FilesCard
                src={dll}
                fileName={"my-file.dll"}
                name={"Coder"}
                date={"16/5/2021"}
                size={"8.1MB"}
              />,
              <FilesCard
                src={dll}
                fileName={"my-file.dll"}
                name={"Coder"}
                date={"16/5/2021"}
                size={"15.1MB"}
              />,
              <FilesCard
                src={dll}
                fileName={"my-file.dll"}
                name={"Coder"}
                date={"16/5/2021"}
                size={"10.1MB"}
              />,
              <FilesCard
                src={pdf}
                fileName={"my-file.pdf"}
                name={"Coder"}
                date={"16/5/2021"}
                size={"8MB"}
              />,
              <FilesCard
                src={avi}
                fileName={"my-file.avi"}
                name={"Admin"}
                date={"16/5/2021"}
                size={"4.1MB"}
              />,
              <FilesCard
                src={psd}
                fileName={"my-file.psd"}
                name={"Abdullah"}
                date={"16/5/2021"}
                size={"15.1MB"}
              />,
              <FilesCard
                src={png}
                fileName={"my-file.png"}
                name={"Coder"}
                date={"16/5/2021"}
                size={"13.1MB"}
              />,
              <FilesCard
                src={pdf}
                fileName={"my-file.pdf"}
                name={"Coder"}
                date={"16/5/2021"}
                size={"15.1MB"}
              />,
              <FilesCard
                src={psd}
                fileName={"my-file.psd"}
                name={"Abdullah"}
                date={"16/5/2021"}
                size={"17.1MB"}
              />,
              <FilesCard
                src={avi}
                fileName={"my-file.avi"}
                name={"Admin"}
                date={"16/5/2021"}
                size={"5.1MB"}
              />,
]

export default allFiles